describe('Add sales invoice', function() {
//login
	it('Add sales invoice', function() {
		cy.visit('https://us.priority-software.com/demus/DEM4/?_disableplugin=1#')
		cy.wait (1000)
		cy.get('input[class="loginlabel_textboxstyle"]').eq(0)
		 .type('QA')
		 .should('have.value', 'QA')		 
		cy.get('input[class="loginlabel_textboxstyle"]').eq(1)
		 .type('123456')
		 .should('have.value', '123456')
//Choose company		 		
		cy.get('button[class="loginlabel_buttonStyle1"]').should('be.enabled')		
		 cy.get('button[class="loginlabel_buttonStyle1"').click()
		cy.get('div[class="choosecompanydlg_textBoxStyle"').click()		
         cy.get('tr[__gwt_row="6"]').eq(6).click()
		 cy.get('div[class="html-face"]').eq(1).click()	
//Add sales invoice	 
        cy.get('#merk_menu_item_4062_5 > .imgContainer > .regular').click()
		cy.get('.priCurrentFieldStyle')
		 .type('100001a')
		 .should('have.value', '100001a')
		 cy.wait (2000)
		 cy.get('[__gwt_row="0"] > .hide-expender > [style="outline-style:none;"] > .formCellStyle > .priFieldStyle').click()
		 cy.wait (2000)
		cy.get('.priCurrentFieldStyle')
		 .type('100-000')
		 .should('have.value', '100-000')
		cy.wait (2000)
		cy.get('.dropdown-item').click()
		cy.wait (2000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.wait (1000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('.priCurrentFieldStyle')
		 .type('10')
		 .should('have.value', '10')
		cy.wait (1000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 755px; top: 0px;"] > svg > g > path').click()
		cy.get('.priCurrentFieldStyle')
		 .type('10')
		 .should('have.value', '10')
		cy.get('.trigger-wrapper > .Button-module_component__2lvSu').click()
		cy.get(':nth-child(1) > :nth-child(1) > .hover-area > .title').click()
		cy.get('.InlineManual_CancelButton').click()
		cy.wait (4000)
		cy.get('.priCurrentFieldStyle')
		 .type('1')
		 .should('have.value', '1')
		cy.get('.priCurrentRowStyle > :nth-child(1) > [style="outline-style:none;"] > .formCellStyle > .priFieldStyle').click()
		cy.wait (2000)
		cy.get('.priCurrentFieldStyle')
		 .type('100-000')
		 .should('have.value', '100-000')
		cy.wait (2000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.wait (1000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.wait (1000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 247px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 183px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.get(':nth-child(4) > div > .formCellStyle > .priCurrentFieldStyle')
		 .type('1')
		 .should('have.value', '1')
		cy.wait (1000)
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.get('[style="width: 9px; height: 7px; z-index: 400; position: absolute; left: 147px; top: 0px;"] > svg > g > path').click()
		cy.get('.searchButtonStyle > #date > path').click()
		cy.get(':nth-child(6) > :nth-child(6) > .datePickerDay').click()
		cy.get(':nth-child(4) > .svg-icon > .svg-tab-image > path').click()

		

})
})